name: Deploy CI

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Pull changes and start docker container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }};
          git pull;
          docker compose down;
          docker compose up -d --build;
          docker rmi $(docker images -f dangling=true -q)

