name: Deploy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Pull changes and start docker container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }};
          git checkout main:
          git pull;
          docker stop tgbot;
          docker rm tgbot;
          docker image rm tgbot;
          docker build -t tgbot .;
          docker run -d --name tgbot tgbot;

